[tool.ruff]
exclude = [
    ".venv",
    ".ruff_cache"
]
line-length = 100
indent-width = 4

[tool.ruff.lint]
select = [
    "F", # Flake8
    "B", # Black
    "I", # isort
    "E", # error
    "W"  # warning
]

ignore = ["F401"]
